name: agile_cards
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #utils
  go_router: ^6.0.0
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  flutter_secure_storage: ^7.0.1
  dio: ^4.0.6
  auto_size_text: ^3.0.0
  fluttertoast: ^8.1.2
  uuid: ^3.0.7
  clipboard: ^0.1.3
  form_field_validator: ^1.1.0
  share_plus: ^6.3.0
  image_picker: ^0.8.6

  # state
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  shared_preferences:
  equatable:
  meta: ^1.3.0
  very_good_analysis: ^3.1.0
  flutter_form_builder: ^7.4.0
  form_builder_validators: ^8.2.0

  #ux
  pull_to_refresh: ^2.0.0
  reorderables: ^0.5.0
  expansion_tile_card: ^2.0.0
  timelines: ^0.1.0
  pluto_grid: ^5.3.0

  #annotation
  json_annotation: ^4.7.0
  copy_with_extension_gen: ^5.0.0

  #ui
  flip_card: ^0.6.0
  stacked_card_carousel: ^0.0.4
  font_awesome_flutter: ^10.3.0

  #firebase
  firebase_core:
  firebase_crashlytics:
  firebase_analytics:
  firebase_performance:
  firebase_storage:
  firebase_dynamic_links:
  firebase_auth:
  firebase_database:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
