name: agile_cards
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #utils
  go_router: ^7.1.1
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  flutter_secure_storage: ^8.0.0
  dio: ^5.1.2
  auto_size_text: ^3.0.0
  fluttertoast: ^8.1.2
  uuid: ^3.0.7
  clipboard: ^0.1.3
  share_plus: ^7.0.1
  image_picker: ^0.8.6
  flutter_svg: ^2.0.6
  flutter_launcher_icons: ^0.13.1

  # state
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  shared_preferences:
  equatable:
  meta: ^1.3.0
  very_good_analysis: ^5.0.0+1
  flutter_form_builder:
  form_builder_validators:

  #ux
  pull_to_refresh: ^2.0.0
  reorderables: ^0.6.0
  expansion_tile_card: ^2.0.0
  timelines: ^0.1.0
  pluto_grid:

  #annotation
  json_annotation: ^4.7.0
  copy_with_extension_gen: ^5.0.0

  #ui
  animate_do: ^3.0.2
  stacked_card_carousel: ^0.0.4
  font_awesome_flutter: ^10.3.0

  #firebase
  firebase_core:
  firebase_crashlytics:
  firebase_analytics:
  firebase_performance:
  firebase_storage:
  firebase_dynamic_links:
  firebase_auth:
  firebase_database:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
